// TODO: Refine
export enum KeyboardShortcut {
  import = 'i',
  settings = ',',
  help = 'h',
  selection = 's',
  colors = 'c',
  queries = 'q',
  meta = 'z',
  audio = 'a',
  details = 'd',
  volumes = 'v',
  matrices = 'm',
  pairings = 'p',
  trajectories = 'T',
  indicators = 'I',
  time = 't',
  timePlayPause = 'space',
  timeBackward = 'p',
  timeForward = 'n',
}
