export enum KeyboardShortcut {
  import = 'i',
  settings = ',',
  help = 'h',
  selection = 's',
  colors = 'c',
  labels = 'z',
  labelsZoom = 'Z',
  audio = 'a',
  details = 'd',
  trajectories = 'x',
  relativeTrajectories = 'r',
  indicators = 'v',
  digested = 'b',
  time = 't',
  timeline = 'T',
  timePlayPause = ' ',
  timeBackward = 'p',
  timeForward = 'n',
}
