export enum KeyboardShortcut {
  import = 'i',
  settings = ',',
  help = 'h',
  selection = 's',
  colors = 'c',
  queries = 'q',
  meta = 'z',
  audio = 'a',
  details = 'd',
  volumes = 'v',
  pairings = 'p',
  matrices = 'm',
  time = 't',
  timePlayPause = 'space',
  timeBackward = 'p',
  timeForward = 'n',
  scatterReset = 'r',
  scatterPrevious = 'k',
  scatterNext = 'j',
}
