
export enum SettingKey {
  version = 'sse-version',
  darkMode = 'sse-dark-mode',
  plotBackground = 'sse-settings-plotBackground',
  timeshift = 'sse-settings-timeshift',
  isDetailsAutoOpen = 'sse-settings-isDetailsAutoOpen',
  isAudioAutoOpen = 'sse-settings-isAudioAutoOpen',
  isAlphaPreview = 'sse-settings-isAlphaPreview',
  isBetaPreview = 'sse-settings-isBetaPreview',
  isTimezoneActive = 'sse-settings-isTimezoneActive',
  isCopyOnSelect2d = 'sse-settings-isCopyOnSelect2d',
  isWebGlScatter2d = 'sse-settings-isWebGlScatter2d',
  isColorMapSwapped = 'sse-settings-isColorMapSwapped',
  spectrogramColorMap = 'sse-settings-spectrogramColorMap',
  audioHost = 'sse-settings-audioHost',
  plotFontSize = 'sse-settings-plotFontSize',
  decibelsDisplay = 'sse-settings-decibelsDisplay',
  legendOverflow = 'sse-settings-legendOverflow',
  labelsSizeHorizontal = 'sse-settings-labelsSizeHorizontal',
  labelsSizeVertical = 'sse-settings-labelsSizeVertical',
  colorsFlavor = 'sse-settings-colorsFlavor',
  colorsAlphaLow = 'sse-settings-colorsAlphaLow',
  colorsAlphaHigh = 'sse-settings-colorsAlphaHigh',
  isHidingMenuOnDraggableToggle = 'sse-settings-isHidingMenuOnDraggableToggle',
  isDevEnabled = 'sse-settings-isDevEnabled',
  devAutoLoadView = 'sse-settings-devAutoLoadView',
  isSelectedPointHighlighted = 'sse-settings-isSelectedPointHighlighted',
  isDetailedExportName = 'sse-settings-isDetailedExportName',
  scatterBorderWidth = 'sse-settings-scatterBorderWidth',
}
