services:
  front:
    build: front
    ports:
      - "8080:8080"

  processing:
    build: processing
    volumes:
      - ${PROJECT}:${PROJECT}
      - ${STORAGE}:/storage
    command:
      - -c${PROJECT}/config.xlsx
      - -s/storage/storage.h5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
