services:
  front:
    build: front
    ports:
      - "8080:8080"
    depends_on:
      - back

  back:
    build: back
    ports:
      - "8081:8081"
    volumes:
      - ./sample:/sample
    depends_on:
      - processing

  processing:
    build: processing
    volumes:
      - ./sample:/sample
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
