version: "3.7"

services:
  front:
    build: front
    ports:
      - "8080:8080"
    depends_on:
      - back

  back:
    build: back
    ports:
      - "8081:8081"
    volumes:
      - ./sample:/sample
