services:
  front:
    build: front
    ports:
      - "8080:8080"
    depends_on:
      - back

  processing:
    build: processing
    volumes:
      - ./sample:/sample
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
