services:
  front:
    image: ghcr.io/sound-scape-explorer/front:latest
    ports:
      - "8080:8080"

  processing:
    image: ghcr.io/sound-scape-explorer/processing:latest
    volumes:
      - ./sample:/sample
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
