services:
  front:
    image: ghcr.io/sound-scape-explorer/front:next
    ports:
      - "8080:8080"
    depends_on:
      - back

  processing:
    image: ghcr.io/sound-scape-explorer/processing:next
    volumes:
      - ./sample:/sample
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
