services:
  front:
    image: ghcr.io/sound-scape-explorer/front:next
    ports:
      - "8080:8080"
    depends_on:
      - back

  back:
    image: ghcr.io/sound-scape-explorer/back:next
    ports:
      - "8081:8081"
    volumes:
      - ./sample:/sample
    depends_on:
      - processing

  processing:
    image: ghcr.io/sound-scape-explorer/processing:next
    volumes:
      - ./sample:/sample
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
