services:
  front:
    image: ghcr.io/sound-scape-explorer/front:latest
    ports:
      - "8080:8080"

  audio:
    image: ghcr.io/sound-scape-explorer/audio:latest
    volumes:
      - ${AUDIO_FOLDER}:/mount/audio
    ports:
      - "3000:3000"
