name: docker-processing

on:
  release:
    types:
      - published
  push:
    branches:
      - 'next/**'

jobs:
  docker-processing-main:
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.ref, 'refs/heads/main' )}}
    steps:

      - run: echo "IMAGE=$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")" >> $GITHUB_ENV

      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:processing"
          push: true
          tags: |
            ghcr.io/sound-scape-explorer/processing:main

  docker-processing-next:
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.ref, 'refs/heads/next' )}}
    steps:

      - run: echo "IMAGE=$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")" >> $GITHUB_ENV

      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:processing"
          push: true
          tags: |
            ghcr.io/sound-scape-explorer/processing:next
